/*
 Navicat Premium Data Transfer

 Source Server         : Mysql
 Source Server Type    : MySQL
 Source Server Version : 100414
 Source Host           : localhost:3306
 Source Schema         : skote

 Target Server Type    : MySQL
 Target Server Version : 100414
 File Encoding         : 65001

 Date: 08/07/2021 16:36:13
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for scr_supers
-- ----------------------------
DROP TABLE IF EXISTS `scr_supers`;
CREATE TABLE `scr_supers`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `1_firstName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_lastName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_idNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_passportNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_maritalStatus` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_birthDate` datetime(0) NULL DEFAULT NULL,
  `1_gender` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_occupation` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_pinNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_nationality` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_tin` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_citizenship` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_residency` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_1_employed` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_1_employer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_1_employerCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_1_departmentCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_1_employeeTerms` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_1_employerNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_2_businessName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_2_natureOfBusiness` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_2_properBusiness` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_3_cell` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_3_workPhone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_3_homePhone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_3_emailAddress` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_4_poBox` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_4_building` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_4_town` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_4_postalCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_5_physicalBuilding` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_5_physicalStreet` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_5_physicalTown` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_5_physicalPostalCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_6_usaStreet` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_6_usaTown` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_6_usaRegion` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `1_6_usaPostalCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_6` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_7` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_8` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_5_height` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_5_weight` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_5_weightStatus` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_7_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_7_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_7_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_7_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_weeklyIncome` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_monthlyIncome` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_sourceOfIncome` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_1_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_1_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_1_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_1_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_1_5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_2_nameOfInsure` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_2_dateOfProposal` datetime(0) NULL DEFAULT NULL,
  `3_2_sumAssured` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_2_acceptedAt` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_2_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_2_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_3_paymentMethod` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_3_paymentFrequency` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_3_debitInstructionDate` datetime(0) NULL DEFAULT NULL,
  `3_3_policyTerm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_3_premiumPayable` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_3_initialPremiumPaymentAccountNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_3_regularPremiumPaymentAccountNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_anb` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_term` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_rate` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_sumAssured` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_monthlyPremium` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_nonMonthlyPremium` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_discountOnNonMonthly` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_monthlyPremium_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_nonMonthlyPremium_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_monthlyPremium_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_nonMonthlyPremium_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_monthlyPremium_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_nonMonthlyPremium_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_monthlyPremium_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_nonMonthlyPremium_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_monthlyPremium_5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_nonMonthlyPremium_5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_monthlyPremium_6` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_nonMonthlyPremium_6` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_premiumInWords` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_1_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_1_1_a` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_1_1_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_1_1_c` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_2_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_2_1_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_2_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_2_2_a` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_2_2_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_2_2_c` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_2_2_d` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_2_2_e` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_2_2_f` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_2_2_g` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_3_a` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_3_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_a` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_a_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_b_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_c` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_c_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_d` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_d_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_e` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_e_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_f` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_f_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_4_g` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `created_at` datetime(0) NULL DEFAULT NULL,
  `updated_at` datetime(0) NULL DEFAULT NULL,
  `4_1_firstName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_surName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_dateOfBirth` datetime(0) NULL DEFAULT NULL,
  `4_1_gender` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_relationship` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_cell` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_benefitShare` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_guadianFullname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_guadianBirthDate` datetime(0) NULL DEFAULT NULL,
  `4_1_guadianTelephone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_firstName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_surName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_dateOfBirth` datetime(0) NULL DEFAULT NULL,
  `4_2_gender` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_relationship` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_cell` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_benefitShare` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_guadianFullname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_guadianBirthDate` datetime(0) NULL DEFAULT NULL,
  `4_2_guadianTelephone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_firstName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_surName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_dateOfBirth` datetime(0) NULL DEFAULT NULL,
  `4_3_gender` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_relationship` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_cell` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_benefitShare` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_guadianFullname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_guadianBirthDate` datetime(0) NULL DEFAULT NULL,
  `4_3_guadianTelephone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_firstName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_surName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_dateOfBirth` datetime(0) NULL DEFAULT NULL,
  `4_4_gender` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_relationship` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_cell` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_benefitShare` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_guadianFullname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_guadianBirthDate` datetime(0) NULL DEFAULT NULL,
  `4_4_guadianTelephone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_5_firstName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_5_surName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_5_dateOfBirth` datetime(0) NULL DEFAULT NULL,
  `4_5_gender` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_5_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_5_relationship` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_5_cell` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_5_benefitShare` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_5_guadianFullname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_5_guadianBirthDate` datetime(0) NULL DEFAULT NULL,
  `4_5_guadianTelephone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_postalAddress` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `code` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 190 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of scr_supers
-- ----------------------------

-- ----------------------------
-- Table structure for scrs
-- ----------------------------
DROP TABLE IF EXISTS `scrs`;
CREATE TABLE `scrs`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `firstName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `lastName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `birthDateOfChild` datetime(0) NULL DEFAULT NULL,
  `childGender` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `relationship` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_firstName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_lastName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_idNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_passportNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_maritalStatus` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_birthDate` datetime(0) NULL DEFAULT NULL,
  `2_gender` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_occupation` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_pinNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_nationality` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_tin` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_citizenship` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_residency` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_1_employed` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_1_employer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_1_employerCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_1_departmentCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_1_employeeTerms` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_1_employerNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_2_businessName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_2_natureOfBusiness` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_2_properBusiness` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_3_cell` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_3_workPhone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_3_homePhone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_3_emailAddress` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_poBox` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_building` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_town` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_4_postalCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_5_physicalBuilding` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_5_physicalStreet` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_5_physicalTown` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_5_physicalPostalCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_6_usaStreet` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_6_usaTown` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_6_usaRegion` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `2_6_usaPostalCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_6` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_7` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_4_8` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_5_height` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_5_weight` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_5_weightStatus` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_7_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_7_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_7_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `3_7_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_weeklyIncome` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_monthlyIncome` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_sourceOfIncome` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_1_5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_nameOfInsure` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_dateOfProposal` datetime(0) NULL DEFAULT NULL,
  `4_2_sumAssured` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_acceptedAt` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_paymentMethod` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_paymentFrequency` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_debitInstructionDate` datetime(0) NULL DEFAULT NULL,
  `4_3_policyTerm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_premiumPayable` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_initialPremiumPaymentAccountNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_3_regularPremiumPaymentAccountNumber` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_anb` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_term` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_rate` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_sumAssured` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_monthlyPremium` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_nonMonthlyPremium` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_discountOnNonMonthly` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_monthlyPremium_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_nonMonthlyPremium_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_monthlyPremium_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_nonMonthlyPremium_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_monthlyPremium_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_nonMonthlyPremium_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_monthlyPremium_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_nonMonthlyPremium_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_monthlyPremium_5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_nonMonthlyPremium_5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_monthlyPremium_6` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_nonMonthlyPremium_6` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_4_premiumInWords` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_firstName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_surname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_dateOfBirth` datetime(0) NULL DEFAULT NULL,
  `5_gender` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_relationshipToMinor` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_cell` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `5_postalAddress` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_1_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_1_1_a` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_1_1_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_1_1_c` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_2_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_2_1_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_2_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_2_2_a` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_2_2_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_2_2_c` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_2_2_d` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_2_2_e` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_2_2_f` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_2_2_g` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_3_a` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_3_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_a` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_a_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_b_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_c` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_c_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_d` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_d_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_e` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_e_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_f` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_f_amount` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `6_4_g` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `created_at` datetime(0) NULL DEFAULT NULL,
  `updated_at` datetime(0) NULL DEFAULT NULL,
  `code` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `4_2_hasProposal` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 134 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of scrs
-- ----------------------------

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `password` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `phone_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `avatar` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `remember_token` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `created_at` datetime(0) NULL DEFAULT NULL,
  `updated_at` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `users_email_unique`(`email`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 849 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES (848, 'bheemcoin@gmail.com', '$2y$10$RyzcneNDbBwFknucRW5CfO1WUxMTEaXKgkopdnoOwflnb1HPkHoli', '+919791947897', NULL, NULL, '2021-06-28 04:35:28', '2021-06-28 06:43:18');

SET FOREIGN_KEY_CHECKS = 1;
